#!/usr/bin/env python3

WIDTH = 800
HEIGHT = 600
BLOCK_SIZE = 20
X_BORDER = 39
Y_BORDER = 29
SNAKE_SPEED = 15
DEFAULT_FOOD_PROBABILITY = 10
DOUBLE_LENGTH_PROBABILITY = 3
BOOST_PROBABILITY = 4
BOOST_COEFFICIENT = 1.5
REVERSE_PROBABILITY = 5
