# WIDTH and HEIGHT must contain to square of BLOCK_SIZE

WIDTH = 800
HEIGHT = 600
BLOCK_SIZE = 20
SNAKE_SPEED = 15
DEFAULT_FOOD_PROBABILITY = 20
DOUBLE_LENGTH_PROBABILITY = 1
SPEED_UP_PROBABILITY = 2
