#!/usr/bin/env python3

WIDTH = 800
HEIGHT = 600
BLOCK_SIZE = 20
SNAKE_SPEED = 10
DEFAULT_FOOD_PROBABILITY = 10
DOUBLE_LENGTH_PROBABILITY = 2
BOOST_PROBABILITY = 4
BOOST_COEFFICIENT = 1.5
REVERSE_PROBABILITY = 5
